import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import HamburgerMenu from "@/components/ui/Navigation/HamburgerMenu";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import Navigation from "@/components/ui/Navigation/Navigation";

const poppins = Poppins({
    weight: ["100", "300", "400", "700"],
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body className={`${poppins.className} bg-body`}>
                    <SignedOut>
                        <div className="flex items-center justify-between p-5">
                            <Image
                                src="/logo.svg"
                                width={50}
                                height={50}
                                alt="GetGroceries logo image"
                            />

                            <HamburgerMenu />
                        </div>
                    </SignedOut>

                    {children}

                    <SignedIn>
                        <Navigation />
                    </SignedIn>
                </body>
            </html>
        </ClerkProvider>
    );
}
